#!/bin/bash
# Copyright (C) 2011 G.P. Halkes
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3, as
# published by the Free Software Foundation.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

DIR="`dirname \"$0\"`"

make -q -C "$DIR" || make -C "$DIR" || exit 1

{ sleep 1 ; sh -c "ddd \"$DIR/.objects/edit\" \"`pgrep -x edit | tail -n1`\"" ; } &
"$DIR/tedit" --W -Cconfig "$@"
